import datetime


azure_blob_token = "?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-02-10T11:26:21Z&st=2024-01-23T03:26:21Z&spr=https&sig=mpe3aTH4DxOM8ZEDo0Loin8OBMnqvrjFUaPAXFVyNjs%3D"
azure_blob_cover = "https://radowski.blob.core.windows.net/cover/<blob_name>"
azure_blob_book = "https://radowski.blob.core.windows.net/book/<blob_name>"
azure_blob_poem = "https://radowski.blob.core.windows.net/poem/<blob_name>"

libro_i_cover = azure_blob_cover.replace("<blob_name>", "libro_i.png")
libro_ii_cover = azure_blob_cover.replace("<blob_name>", "libro_ii.png")
poemas_para_mi_cover = azure_blob_cover.replace("<blob_name>", "poemas_para_mi.png")
libro_i_pdf = azure_blob_book.replace("<blob_name>", "libro_i.pdf")
libro_ii_pdf = azure_blob_book.replace("<blob_name>", "libro_i.pdf")
poemas_para_mi_pdf = azure_blob_book.replace("<blob_name>", "poemas_para_mi.pdf")
libro_i__book_i_pdf = azure_blob_book.replace("<blob_name>", "libro_i__book_i.pdf")
libro_ii__book_ii_pdf = azure_blob_book.replace("<blob_name>", "libro_ii__book_ii.pdf")
poemas_para_mi__poems_for_me_pdf = azure_blob_book.replace(
    "<blob_name>", "poemas_para_mi__poems_for_me.pdf"
)

content_book_ii = [
    {
        "poem_id": 1,
        "name": "dios",
        "title": "Dios",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 2,
        "name": "identidad",
        "title": "Identidad",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 3,
        "name": "spica",
        "title": "Spica",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 4,
        "name": "moral",
        "title": "Moral",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 5,
        "name": "exhortacion",
        "title": "Exhortación",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 6,
        "name": "voz_de_escritor",
        "title": "Voz de Escritor",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 7,
        "name": "derrotismo",
        "title": "Derrotismo",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 8,
        "name": "utopia_de_ratas",
        "title": "Utopía de Ratas",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 9,
        "name": "reflexion_ii",
        "title": "Reflexión II",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 10,
        "name": "reflexion_iii",
        "title": "Reflexión III",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 11,
        "name": "reflexion_iv",
        "title": "Reflexión IV",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 12,
        "name": "reflexion_xii",
        "title": "Reflexión XII",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 13,
        "name": "no_es_suficiente",
        "title": "No es Suficiente",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 14,
        "name": "checa",
        "title": "Checa",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 15,
        "name": "odio",
        "title": "Odio",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 16,
        "name": "ella",
        "title": "Ella",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 17,
        "name": "media_de_lucky_rojo",
        "title": "Media de Lucky Rojo",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 18,
        "name": "reflexion_ix",
        "title": "Reflexión IX",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
content_book_i = [
    {
        "poem_id": 19,
        "name": "nostalgia",
        "title": "Nostalgia",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 20,
        "name": "un_mundo_triste",
        "title": "Un Mundo Triste",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 21,
        "name": "acrilico",
        "title": "Acrílico",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 22,
        "name": "cliche",
        "title": "Cliché",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 23,
        "name": "cliche_ii",
        "title": "Cliché II",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 24,
        "name": "dientes",
        "title": "Dientes",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 25,
        "name": "monotonia",
        "title": "Monotonía",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 26,
        "name": "stitch",
        "title": "Stitch",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 27,
        "name": "cansancio",
        "title": "Cansancio",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 28,
        "name": "otra_forma_de_dolor",
        "title": "Otra Forma de Dolor",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 29,
        "name": "caribe",
        "title": "Caribe",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 30,
        "name": "inspiracion",
        "title": "Inspiración",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 31,
        "name": "marea_baja",
        "title": "Marea Baja",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 32,
        "name": "la_casa_de_las_goteras",
        "title": "La Casa de las Goteras",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 33,
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 34,
        "name": "die_rosenrot",
        "title": "Die Rosenrot",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 35,
        "name": "reflexion_x",
        "title": "Reflexión X",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_poemas_para_mi = [
    {
        "poem_id": 36,
        "name": "entre_dientes",
        "title": "Entre Dientes",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 37,
        "name": "lounova",
        "title": "Lounová",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 38,
        "name": "novia",
        "title": "Novia",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 39,
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 40,
        "name": "miketta",
        "title": "Miketta",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 41,
        "name": "manipulacion",
        "title": "Manipulación",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 42,
        "name": "insuperable",
        "title": "Insuperable",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 43,
        "name": "abuela",
        "title": "Abuela",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 44,
        "name": "balcon",
        "title": "Balcón",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_book_ii_eng = [
    {
        "poem_id": 1,
        "name": "god",
        "title": "God",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 2,
        "name": "identity",
        "title": "Identity",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 3,
        "name": "spica",
        "title": "Spica",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 4,
        "name": "moral",
        "title": "Moral",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 5,
        "name": "exhortation",
        "title": "Exhortation",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 6,
        "name": "writers_voice",
        "title": "Writer's Voice",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 7,
        "name": "defeatism",
        "title": "Defeatism",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 8,
        "name": "rat_utopia",
        "title": "Rat Utopia",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 9,
        "name": "reflection_ii",
        "title": "Reflection II",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 10,
        "name": "reflection_iii",
        "title": "Reflection III",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 11,
        "name": "reflection_iv",
        "title": "Reflection IV",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 12,
        "name": "reflection_xii",
        "title": "Reflection XII",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 13,
        "name": "its_not_enough",
        "title": "It's not enough",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 14,
        "name": "czech",
        "title": "Czech",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 15,
        "name": "hatred",
        "title": "Hatred",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 16,
        "name": "she",
        "title": "She",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 17,
        "name": "half_red_lucky_pack",
        "title": "Half Red Lucky Pack",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 18,
        "name": "reflection_ix",
        "title": "Reflection IX",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_book_i_eng = [
    {
        "poem_id": 19,
        "name": "nostalgia",
        "title": "Nostalgia",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 20,
        "name": "a_sad_world",
        "title": "A Sad World",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 21,
        "name": "acrylic",
        "title": "Acrylic",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 22,
        "name": "cliche",
        "title": "Cliché",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 23,
        "name": "cliche_ii",
        "title": "Cliché II",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 24,
        "name": "teeth",
        "title": "Teeth",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 25,
        "name": "monotony",
        "title": "Monotony",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 26,
        "name": "stitch",
        "title": "Stitch",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 27,
        "name": "weariness",
        "title": "Weariness",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 28,
        "name": "another_form_of_pain",
        "title": "Another Form of Pain",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 29,
        "name": "caribbean",
        "title": "Caribbean",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 30,
        "name": "inspiration",
        "title": "Inspiration",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 31,
        "name": "low_tide",
        "title": "Low Tide",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 32,
        "name": "the_house_of_leaks",
        "title": "The House of Leaks",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 33,
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 34,
        "name": "the_red_rose",
        "title": "The Red rose",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 35,
        "name": "reflection_x",
        "title": "Reflection X",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_poemas_para_mi_eng = [
    {
        "poem_id": 36,
        "name": "between_teeth",
        "title": "Between Teeth",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 37,
        "name": "lounova",
        "title": "Lounová",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 38,
        "name": "girlfriend",
        "title": "Girlfriend",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 39,
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 40,
        "name": "miketta",
        "title": "Miketta",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 41,
        "name": "manipulation",
        "title": "Manipulation",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 42,
        "name": "unforgettable",
        "title": "Unforgettable",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 43,
        "name": "grandmother",
        "title": "Grandmother",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 44,
        "name": "balcony",
        "title": "Balcony",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]


book_content = [
    {"content_id": 1, "book_id": 1},
    {"content_id": 2, "book_id": 1},
    {"content_id": 3, "book_id": 1},
    {"content_id": 4, "book_id": 1},
    {"content_id": 5, "book_id": 1},
    {"content_id": 6, "book_id": 1},
    {"content_id": 7, "book_id": 1},
    {"content_id": 8, "book_id": 1},
    {"content_id": 9, "book_id": 1},
    {"content_id": 10, "book_id": 1},
    {"content_id": 11, "book_id": 1},
    {"content_id": 12, "book_id": 1},
    {"content_id": 13, "book_id": 1},
    {"content_id": 14, "book_id": 1},
    {"content_id": 15, "book_id": 1},
    {"content_id": 16, "book_id": 1},
    {"content_id": 17, "book_id": 1},
    {"content_id": 18, "book_id": 1},
    {"content_id": 19, "book_id": 2},
    {"content_id": 20, "book_id": 2},
    {"content_id": 21, "book_id": 2},
    {"content_id": 22, "book_id": 2},
    {"content_id": 23, "book_id": 2},
    {"content_id": 24, "book_id": 2},
    {"content_id": 25, "book_id": 2},
    {"content_id": 26, "book_id": 2},
    {"content_id": 27, "book_id": 2},
    {"content_id": 28, "book_id": 2},
    {"content_id": 29, "book_id": 2},
    {"content_id": 30, "book_id": 2},
    {"content_id": 31, "book_id": 2},
    {"content_id": 32, "book_id": 2},
    {"content_id": 33, "book_id": 2},
    {"content_id": 34, "book_id": 2},
    {"content_id": 35, "book_id": 2},
    {"content_id": 36, "book_id": 3},
    {"content_id": 37, "book_id": 3},
    {"content_id": 38, "book_id": 3},
    {"content_id": 39, "book_id": 3},
    {"content_id": 40, "book_id": 3},
    {"content_id": 41, "book_id": 3},
    {"content_id": 42, "book_id": 3},
    {"content_id": 43, "book_id": 3},
    {"content_id": 44, "book_id": 3},
    {"content_id": 45, "book_id": 4},
    {"content_id": 46, "book_id": 4},
    {"content_id": 47, "book_id": 4},
    {"content_id": 48, "book_id": 4},
    {"content_id": 49, "book_id": 4},
    {"content_id": 50, "book_id": 4},
    {"content_id": 51, "book_id": 4},
    {"content_id": 52, "book_id": 4},
    {"content_id": 53, "book_id": 4},
    {"content_id": 54, "book_id": 4},
    {"content_id": 55, "book_id": 4},
    {"content_id": 56, "book_id": 4},
    {"content_id": 57, "book_id": 4},
    {"content_id": 58, "book_id": 4},
    {"content_id": 59, "book_id": 4},
    {"content_id": 60, "book_id": 4},
    {"content_id": 61, "book_id": 4},
    {"content_id": 62, "book_id": 4},
    {"content_id": 63, "book_id": 5},
    {"content_id": 64, "book_id": 5},
    {"content_id": 65, "book_id": 5},
    {"content_id": 66, "book_id": 5},
    {"content_id": 67, "book_id": 5},
    {"content_id": 68, "book_id": 5},
    {"content_id": 69, "book_id": 5},
    {"content_id": 70, "book_id": 5},
    {"content_id": 71, "book_id": 5},
    {"content_id": 72, "book_id": 5},
    {"content_id": 73, "book_id": 5},
    {"content_id": 74, "book_id": 5},
    {"content_id": 75, "book_id": 5},
    {"content_id": 76, "book_id": 5},
    {"content_id": 77, "book_id": 5},
    {"content_id": 78, "book_id": 5},
    {"content_id": 79, "book_id": 5},
    {"content_id": 80, "book_id": 6},
    {"content_id": 81, "book_id": 6},
    {"content_id": 82, "book_id": 6},
    {"content_id": 83, "book_id": 6},
    {"content_id": 84, "book_id": 6},
    {"content_id": 85, "book_id": 6},
    {"content_id": 86, "book_id": 6},
    {"content_id": 87, "book_id": 6},
    {"content_id": 88, "book_id": 6},
]

language = [
    {"id": 1, "name": "spanish", "original_name": "español"},
    {"id": 2, "name": "english", "original_name": "english"},
]


book = [
    {
        "name": "libro_ii",
        "title": "Libro II",
        "pdf_url": libro_ii_pdf,
        "cover_url": libro_ii_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_i",
        "title": "Libro I",
        "pdf_url": libro_i_pdf,
        "cover_url": libro_i_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "poemas_para_mi",
        "title": "Poemas para mí",
        "pdf_url": poemas_para_mi_pdf,
        "cover_url": poemas_para_mi_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_ii__book_ii",
        "title": "Libro II | Book II",
        "pdf_url": libro_ii__book_ii_pdf,
        "cover_url": libro_ii_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_i__book_i",
        "title": "Libro I | Book I",
        "pdf_url": libro_i__book_i_pdf,
        "cover_url": libro_i_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "poemas_para_mi_poems_for_me",
        "title": "Poemas para mí | Poems for me",
        "pdf_url": poemas_para_mi__poems_for_me_pdf,
        "cover_url": poemas_para_mi_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_libro_ii = [
    {
        "name": "dios",
        "title": "Dios",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "identidad",
        "title": "Identidad",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "spica",
        "title": "Spica",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "moral",
        "title": "Moral",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "exhortacion",
        "title": "Exhortación",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "voz_de_escritor",
        "title": "Voz de Escritor",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "derrotismo",
        "title": "Derrotismo",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "utopia_de_ratas",
        "title": "Utopía de Ratas",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_II",
        "title": "Reflexión II",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_III",
        "title": "Reflexión III",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_IV",
        "title": "Reflexión IV",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_XII",
        "title": "Reflexión XII",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "no_es_suficiente",
        "title": "No es Suficiente",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "checa",
        "title": "Checa",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "odio",
        "title": "Odio",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "ella",
        "title": "Ella",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "media_de_lucky_rojo",
        "title": "Media de Lucky Rojo",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_IX",
        "title": "Reflexión IX",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_libro_i = [
    {
        "name": "nostalgia",
        "title": "Nostalgia",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "un_mundo_triste",
        "title": "Un Mundo Triste",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "acrilico",
        "title": "Acrílico",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche",
        "title": "Cliché",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche_II",
        "title": "Cliché II",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "dientes",
        "title": "Dientes",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "monotonia",
        "title": "Monotonía",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "stitch",
        "title": "Stitch",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cansancio",
        "title": "Cansancio",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "otra_forma_de_dolor",
        "title": "Otra Forma de Dolor",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "caribe",
        "title": "Caribe",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "inspiracion",
        "title": "Inspiración",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "marea_baja",
        "title": "Marea Baja",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "la_casa_de_las_goteras",
        "title": "La Casa de las Goteras",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "die_rosenrot",
        "title": "Die Rosenrot",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_X",
        "title": "Reflexión X",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_poemas_para_mi = [
    {
        "name": "entre_dientes",
        "title": "Entre Dientes",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "lounova",
        "title": "Lounová",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "novia",
        "title": "Novia",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "miketta",
        "title": "Miketta",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "manipulacion",
        "title": "Manipulación",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "insuperable",
        "title": "Insuperable",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "abuela",
        "title": "Abuela",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "balcon",
        "title": "Balcón",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_image_book_ii = [
    {
        "content_id": 1,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dios.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 2,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'identidad.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 3,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'spica.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 4,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'moral.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 5,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'exhortacion.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 6,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'voz_de_escritor.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 7,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'derrotismo.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 8,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'utopia_de_ratas_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 8,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'utopia_de_ratas_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 9,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_ii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 10,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_iii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 11,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_iv.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 12,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_xii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 13,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'no_es_suficiente.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 14,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'checa.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 15,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'odio.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 16,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'ella.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 17,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'media_de_lucky_rojo.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 18,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_ix.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
content_image_book_i = [
    {
        "content_id": 19,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'nostalgia.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 20,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'un_mundo_triste.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 21,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'acrilico.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 22,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cliche.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 23,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cliche_ii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 24,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dientes_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 24,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dientes_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 25,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'monotonia_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 25,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'monotonia_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 26,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'stitch.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 27,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cansancio_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 27,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cansancio_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 28,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'otra_forma_de_dolor_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 28,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'otra_forma_de_dolor_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 29,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 29,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 29,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe_p3.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 30,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'inspiracion_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 30,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'inspiracion_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 31,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'marea_baja_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 31,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'marea_baja_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 32,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 32,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 32,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras_p3.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 33,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'femme_fatale.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 34,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'die_rosenrot_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 34,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'die_rosenrot_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 35,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_x.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_image_poemas_para_mi = [
    {
        "content_id": 36,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'entre_dientes.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 37,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'lounova_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 37,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'lounova_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 38,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'novia.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 39,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 39,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 39,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 40,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'miketta_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 40,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'miketta_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 41,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'manipulacion.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 42,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'insuperable_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 42,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'insuperable_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 43,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'abuela_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 43,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'abuela_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 44,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'balcon.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
poem = poems_libro_ii + poems_libro_i + poems_poemas_para_mi
content = (
    content_book_ii
    + content_book_i
    + content_poemas_para_mi
    + content_book_i_eng
    + content_book_ii_eng
    + content_poemas_para_mi_eng
)
content_image = (
    content_image_book_ii + content_image_poemas_para_mi + content_image_book_i
)
