import datetime


azure_blob_token = "?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-02-10T11:26:21Z&st=2024-01-23T03:26:21Z&spr=https&sig=mpe3aTH4DxOM8ZEDo0Loin8OBMnqvrjFUaPAXFVyNjs%3D"
azure_blob_cover = "https://radowski.blob.core.windows.net/cover/<blob_name>"
azure_blob_book = "https://radowski.blob.core.windows.net/book/<blob_name>"
azure_blob_poem = "https://radowski.blob.core.windows.net/poem/<blob_name>"

libro_i_cover = azure_blob_cover.replace("<blob_name>", "libro_i.png")
libro_ii_cover = azure_blob_cover.replace("<blob_name>", "libro_ii.png")
poemas_para_mi_cover = azure_blob_cover.replace("<blob_name>", "poemas_para_mi.png")
libro_i_pdf = azure_blob_book.replace("<blob_name>", "libro_i.pdf")
libro_ii_pdf = azure_blob_book.replace("<blob_name>", "libro_i.pdf")
poemas_para_mi_pdf = azure_blob_book.replace("<blob_name>", "poemas_para_mi.pdf")
libro_i__book_i_pdf = azure_blob_book.replace("<blob_name>", "libro_i__book_i.pdf")
libro_ii__book_ii_pdf = azure_blob_book.replace("<blob_name>", "libro_ii__book_ii.pdf")
poemas_para_mi__poems_for_me_pdf = azure_blob_book.replace(
    "<blob_name>", "poemas_para_mi__poems_for_me.pdf"
)

content_book_ii = [
    {
        "poem_id": 1,
        "name": "dios",
        "title": "Dios",
        "body": "No me sanes.\nQuiero la tristeza,\nquiero la depresión;\nson mis musas,\nno te las lleves.\nNo me llenes,\nestoy tan lleno,\nque no acepto más.\nSiento arcadas\n\ncuando me hablan de propósitos.\nQuisiera vomitar,\ndejar mi mente en blanco,\nignorarlo todo\ny —tal vez— ser feliz",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 2,
        "name": "identidad",
        "title": "Identidad",
        "body": "Explora la tormenta.\nTócate y siente\ncomo todo es\nviento, arena y mugre;\nuna temporada seca,\notra húmeda.\nEres un péndulo\nque va y viene\nentre llanto e ira;\na veces asceta,\na veces pecadora.\nDe cálida a fría\nte revuelves a ti misma.\nNunca constante,\ncada vez más pesada\nte cuesta oscilar\n¿Qué eres?\nNo el tú;\nsino la infinita suma\nde lo que te rodea:\nimpulsos finitos,\nvoluntades ajenas.\nCuando te detengas,\nen equilibrio,\nte darás cuenta.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 3,
        "name": "spica",
        "title": "Spica",
        "body": "Tú,\nartista y musa,\ndicotomía imposible.\nEntre tu culto y lo celestial,\nprefiero la condena.\nMártir por ti,\nque velada\nentre el cielo y la tierra,\nacoges bajo tu sombra \na los inconformes.\nEres para los hastiados \ndel alba y del crepúsculo\nla salvación de lo cotidiano,\nnuestro eclipse eterno.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 4,
        "name": "moral",
        "title": "Moral",
        "body": "Siempre se puede empeorar,\ncaer más hondo.\nLa luz al final del túnel queda atrás\ny te preguntas:\n¿alguna vez tocaré fondo?\nSe cae por tanto tiempo \nque más arriba o más abajo\nno tiene sentido;\nmejor o peor no hace diferencia.\nPiensas:\n¿qué debo hacer?\n―No hagas.\nSé, existe.\nDisfruta tu maldad, tu bondad,\nlo que seas;\ncomo sea,\npronto\nchocarás con la sima.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 5,
        "name": "exhortacion",
        "title": "Exhortación",
        "body": "Amor, desastre.\nEntre todos los desiertos\nel cactus pica al sol,\nsangra y quema la tierra.\nLas sandalias de la esfinge\nno la protegen de las llamas.\nAbandonadas\n―poesía y música―\nenterradas entre dunas.\nAquellos que lograron salir\nfueron alcanzados por la sombra.\nMiles de notas, ritmos y acordes\napagados por una tormenta de arena,\ncomo lluvia de balas,\nun genocidio artístico.\nA todos se les da una vida,\npero quiénes pueden llegar a ser inmortales.\nEscribe, talla, grita, graba.\nArtista, tus días están contados.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 6,
        "name": "voz_de_escritor",
        "title": "Voz de Escritor",
        "body": "Encontré mi voz de escritor.\nEs gutural,\n―apagada y rasposa―\nllena de pesimismo.\n\nProclama:\n—La ignorancia te hace feliz.\n\nPor eso \ncuando te llame\nignórame \ny ve\nhacia donde el ruido blanco\nopaque mi voz.\n\nSiempre que te invite,\ncon una mirada derrotista,\na reflexionar\nsobre la vida,\ntápate los ojos\ny aléjate de mí.\n\n¿Pero, por qué?\nSigues leyendo.\n\nSigue mi voz\nte libraré de la felicidad.\n\nDesde un rincón\nte llamo a la sombra\ndonde todo es conocimiento.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 7,
        "name": "derrotismo",
        "title": "Derrotismo",
        "body": "La vida empieza a mitad de camino\ncuando decides entre \nser el fruto más rojo en la copa\no regresar y no germinar.\nDecidí regresar, no serlo;\ndescender en la jerarquía.\nAdvertir, convencer a los demás\nde la inminente trampa:\narriba sólo los esperaba ser devorados\no ser ignorados;\neventualmente caer y pudrirse.\nDos caminos que llevan\na la misma fosa de estiércol\npara nutrir nuevamente el ciclo.\nNo quise más esfuerzo en vano\nasí que encontré las raíces,\nen lo más profundo.\nAcabado, me ahogué en la tierra\ny no tuve más pretensiones \nde ver el sol nuevamente.\nInundé de lágrimas aquel árbol seco y fatigado.\nDescubrí que\nlas penitencias acarreadas por el conocimiento \nson la soledad y la tristeza,\nel fracaso.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 8,
        "name": "utopia_de_ratas",
        "title": "Utopía de Ratas",
        "body": "En el pináculo del desarrollo,\nmanos plásticas moldean la moral:\nLo masculino \nes forzado a lo femenino,\nque a su vez \nmarcha a su encuentro;\nen el centro se unen\ny desconcertados,\nellos mismos\nya no son.\nAlienados quieren llorar,\nno pueden;\nno hay emociones,\nsolo autómatas\nreaccionando a estímulos.\nEl amor, el odio;\nlas ambiciones, lo humano:\nconstrucciones sociales,\ndefectos del sistema.\nEl poder vence a la competencia\ny las jerarquías, corruptas,\nse vienen abajo.\nSe culpa a izquierda, a derecha;\nal Diablo, a Dios.\nEllos hace rato se volvieron indiferentes.\nPor otro lado, \nBaco se embriaga\ny disfruta el panorama:\n\nposapocalíptico, posmoderno;\nsin roles, sin identidad.\nLa anarquía anhelada:\nUna utopía de ratas.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 9,
        "name": "reflexion_ii",
        "title": "Reflexión II",
        "body": "Eludir lo inexorable\nes hablar de Dios.\nHablar de Dios es \npensar fuera del tiempo.\nPensar fuera del tiempo\nes soñar.\nSoñar es fantasear\nque los problemas de la vida\nse esfuman escribiendo.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 10,
        "name": "reflexion_iii",
        "title": "Reflexión III",
        "body": "El artista no está en la obra,\nel artista está en el alma:\nentre la mente y el corazón,\npor los pulmones,\ndebajo del esternón;\ndonde el cigarro,\ndespués de cada calada,\ndeja una brasa encendida.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 11,
        "name": "reflexion_iv",
        "title": "Reflexión IV",
        "body": "De noche \nen la playa\nel humo se disipa \nde forma mágica;\nadquiere otra actitud,\ntrata de imitar la serenidad del mar.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 12,
        "name": "reflexion_xii",
        "title": "Reflexión XII",
        "body": "Oscilo entre lo malo y lo peor;\nno ser la mejor versión de mí mismo,\ny no querer serlo.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 13,
        "name": "no_es_suficiente",
        "title": "No es Suficiente",
        "body": "Es curioso\nque no ser la mejor\nversión de ti mismo\nte haga malo.\n\nY no querer serlo\nte vuelva peor.\n\nLo desconcertante \nes que \npara ser bueno\nno basta solo con querer serlo.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 14,
        "name": "checa",
        "title": "Checa",
        "body": "El primer paso\npara superar una adicción\nes aceptarla.\n\nNo se puede disimular\nuna borrachera\ncreyendo estar sobrio.\n\nPara superarte\ndebo aceptar\nque hay partes tuyas\nque no puedo olvidar.\n\nY no es la obsesión por ti,\nsino de lo que representas:\n\nLa idealización de una mujer;\nla musa perfecta.\n\nEl eterno capricho\nde querer\nlo que no puedo alcanzar.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 15,
        "name": "odio",
        "title": "Odio",
        "body": "Me raparé las cejas\ny rasgaré mis prendas;\ny vuelto un completo asceta,\nhermético,\ncerraré la llave de mi alma.\nNo más efluvios de emociones;\nestancadas,\nme volverán carroña.\nSarnoso y callejero\naullaré a la luna\ny sin decoro mostraré indulgencia\npor mi propia debilidad.\n\nNo hay piedad\nen la sabiduría.\nNo hay sabiduría\nen el cansancio;\ntan aburrido de lo común,\ntan cansado del fracaso.\n\nSin historias\nlo mío son palabras recurrentes,\nfrases vagamente unidas;\ncolores intensos\nque abstrajeron todo a figuras,\nla búsqueda de un significado\nque me lleva a la nada,\nforzar un pensamiento\nvulgarizando el intelecto;\nel odio por mí mismo.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 16,
        "name": "ella",
        "title": "Ella",
        "body": "La amaste, a tu manera.\nBajo yugo desigual\nquebraste su cuello.\nY con juramentos\nprometiste cambio,\npero no de tu parte.\nLa engañaste\ny su fe ciega exacerbó su enajenación.\nDe artista a musa\ncambió su mirada:\nsu brillo, sus ojos.\nSe convirtió en tu modelo.\nTransfigurada,\nla consagraste a tu altar\njunto a las Pléyades\ndonde hoy reposa\ndespojada de su cuerpo;\nque, sepultado por el tiempo,\nsin cruz ni epitafio,\nfue olvidado.\n¿Descansará en paz?\n¿Quién era ella?\nLa novia de …",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 17,
        "name": "media_de_lucky_rojo",
        "title": "Media de Lucky Rojo",
        "body": "Un cigarro.\nHablamos del amor y del alma.\nNo los conocemos, ¿quién sí?\nSin embargo, habló de su ex\ny yo de la que nunca he tenido.\n\nDos cigarros.\nHablamos de la otredad:\ntodos se conocen,\npero nadie entiende a nadie.\n—Jamás seremos amigos realmente.\n—No pretendo que lo seamos.\n\nTres cigarros.\nRecurrió a los golpes,\nignoró palabras.\nPuños que hablan\nde resentimientos añejos.\nYo solo observo.\n\nCuatro cigarros.\nPalabras por humo.\nMatamos el tiempo,\nquemamos tabaco.\nNos miramos, nos reímos;\nmiramos al cielo,\nexhalamos.\n\nCinco cigarros.\n—El último es sagrado.\n\nSilencio,\nsímbolo de nuestra amistad.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 18,
        "name": "reflexion_ix",
        "title": "Reflexión IX",
        "body": "“Más sabe el diablo\npor viejo\nque por diablo”.\nSi la sabiduría\nque solo los eones\npueden traer\nno lo han movido hacia un cambio,\n¿por qué debería yo\nbuscar virtud\nen la santidad?",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
content_book_i = [
    {
        "poem_id": 19,
        "name": "nostalgia",
        "title": "Nostalgia",
        "body": "Recuerdo…\nlos buenos tiempos pasados\ncomo pinceladas opacas\nsobre un lienzo gris.\n\nMis traumas,\nexplanadas de negro;\nconstantemente sueño\ncon el vacío de la noche.\n\nPesadillas recurrentes,\nen micro sueños\nque parecen eternos.\n\nLibido ahogada\npor parálisis de sueño.\n\nSin placer en lo banal,\nse deprimen los sentidos;\natrofiados,\nya no perciben\nlas cosas bellas de la vida.\n\nInsensible a los matices,\nsolo descanso\nentre ruido blanco.\n\nSolo la música\ntrae color\na mis recuerdos.\n\nY solo tú\ntraes\nel verde y rojo\nque necesito\npara no estar triste.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 20,
        "name": "un_mundo_triste",
        "title": "Un Mundo Triste",
        "body": "Un mundo triste\ndonde la gente aprende,\ndonde la gente crece.\n\nLlegan al límite\nde sus capacidades,\na la cúspide\ndel conocimiento.\n\nAgobiados por\nlas preguntas\nde antaño\nencuentran las\nrespuestas de siempre:\n\nQue no hay destino;\nque todo es azar.\n\nQue cualquier cosa es correcta\nsi se puede justificar.\n\nY aunque todo es relativo\ny nada sea verdad,\n\nel propósito de la vida\nsigue siendo\nla muerte.\n\nSolo con certeza de ello,\nviviendo en un mundo así,\n¿para qué prolongar\nlo inexorable?",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 21,
        "name": "acrilico",
        "title": "Acrílico",
        "body": "Soñé con el abismo,\notra vez.\nCada vez más oscuro\ny cerca de mí.\n\nAl borde de la cornisa\ndescendiendo en\nen espiral,\ny cada noche,\nantes de despertar,\nme detengo\ny observo el cielo,\n\nOpaco y gris,\ncomo con un amanecer distante;\napagado y sordo,\nlloviendo siempre aquí.\n\nSoñé con el abismo,\notra vez.\nCada vez más oscuro\ny cerca de mí.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 22,
        "name": "cliche",
        "title": "Cliché",
        "body": "Impostora,\naunque seas plástica\neres la flor\nque más atrae\nzánganos.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 23,
        "name": "cliche_ii",
        "title": "Cliché II",
        "body": "¿Mångata?\nNo más que\nel reflejo tenue\nsobre charcos\nagonizantes.\n\nSe secan bajo el sol\ny desaparece la evidencia\nde tu brillo nocturno.\n\n¿Mångata,\ncómo que inmortal?\nSi dependes\nde lo efímero\npara ser visible.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 24,
        "name": "dientes",
        "title": "Dientes",
        "body": "Me quise despedir\ncon una carta origami.\nNo la hice,\nlos tiempos no me dieron;\ndices que no sé medirlos,\nque no sé medirme.\n\nTe iba a hacer un girasol,\no un gladiolo;\nverde, blanco y rojo.\n—Recuerdo lo que me dices\naunque acuses a mi memoria\nde ser peor que la tuya—.\n\nDentro iba a escribir\nque no buscaba simplemente\nuna amistad “literaria”.\nQue quería más\nazoteas,\nmás asientos traseros,\nmás rincones de cocina,\nbesos sobre vidrios,\ncicatrices y poemas.\n\nLo iba a escribir,\npero hoy\nte acompañé en el bus,\ny me mordiste,\nno lo esperaba.\nMe arrepentí.\nTus dientes me convencieron\nque no es necesario\npresionarte\npara encontrar en ti\nuna musa.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 25,
        "name": "monotonia",
        "title": "Monotonía",
        "body": "¿Cómo sigue todo con él?\nNo quieres hablar de eso, es complicado.\nEntiendo, entiendo.\n\nNo quiero incomodarte\nni ponerte a pensar\nen cosas poco placenteras.\n\nSolo quería saber de ti\nporque ayer\nme dijiste que\nes difícil no caer en la monotonía.\n\nHablaste de su amor,\nsobre cómo ha “madurado”;\nlo “estable” que es.\n\nEufemismos\npara maquillar el rescoldo\nde una pasión\nque ahogó su llama.\n\nLo sé,\nquieres volver a sentirlo:\nel calor del fuego\nantes de que queme.\n\nPero tienes miedo\nde acercarte tanto que\nno puedas apagarme\ncon un soplido.\n\nPero tranquila,\nmis intenciones no son\nmanipularte para que lo botes;\nsolo quiero que no dejes de ser\nmi musa.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 26,
        "name": "stitch",
        "title": "Stitch",
        "body": "Hola,\n¿cómo vas?\nTal vez te alegre saber\nque he vuelto a escribir.\n¿Y tú, qué has hecho con tu vida?\n\nEspero no haberte dañado la mente\ncon eso de reflexionar\nsobre ella,\n\npues yo\nhe estado sintiendo ansias\nal ver el cielo;\nme resulta difícil creer\nque pueda disipar la inconformidad\nque algunos sienten\npor la vida que no escogieron vivir.\n\n¿Quién la habrá escogido para mí?\n\nNo importa,\nsi es que al final\nmi ansiedad no viene de ahí.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 27,
        "name": "cansancio",
        "title": "Cansancio",
        "body": "Un ojo entreabierto\ny otro desconectado de la mente.\n\nA los de color negro\nse les ha privado\nla riqueza\nde una vida cromática.\n\nReloj de pulsera\nde cuero sadomasoquista.\n\nEl paso del tiempo\nes la herramienta de placer\npara quien disfruta\ndel sufrimiento de lo efímero.\n\nLágrimas erosionando\nla piel porosa entre tabique y pómulos.\n\nUn rostro tan golpeado\npor las gentiles\ngotas de rocío\nque traen las madrugadas.\n\nMadrugadas que espero despierto\nporque en mí no hay deseo de descansar.\n\nTu bofetada de realidad\nfue tan dura\nque mi imaginación ya ni se atreve\na soñar que soy tu dueño.\n\nSi no puedo soñarme\nsiendo feliz,\n¿qué sentido tiene dormir?",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 28,
        "name": "otra_forma_de_dolor",
        "title": "Otra Forma de Dolor",
        "body": "La insensibilidad\nque trae el dolor\nno te vuelve\ninmune a la tristeza,\n\nporque el verdadero\nsufrimiento viene\nde la mente\n\n¿No me crees?\n\nCuando se cruza el umbral\nde dolor\nlos cuerpos\nceden a la insensibilidad.\n\nEmbriagado de adrenalina,\npodría tener\nlas tripas colgando\nen la acera\nsin sentir dolor\n\nTe lo digo,\nDios no fue\ntan cruel al crear al ser\nhumano después de todo.\n\n¿Pero, qué\nhizo el hombre?\n\nAlimentó su mente\ncon el fruto del\nárbol del conocimiento.\n\nY ahora\nconsciente,\nviendo tripas escurriéndose\npor la alcantarilla;\n\ngritos, llanto\ny maldiciones\n¿de dónde sale este dolor?\n\nYa te lo he dicho:\n\n“la ignorancia te…”\n\n¿Que por qué te digo esto?\n\nPara explicarte,\n\nque a pesar\nde que tu comentario\nno me haga sentir mal,\nsoy lo suficientemente inteligente\npara saber que\ndebería.\n\nY eso\nme pone triste.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 29,
        "name": "caribe",
        "title": "Caribe",
        "body": "Promuevo la idea\nde una obra opaca\ny visceral\nque cualquiera\nsea capaz de relacionar con\nla belleza\nque nace del dolor.\n\nPero la gente\nno quiere esforzarse\nen apreciar detalles,\n\nme tildan de hereje\ncuando trato de ejercitar\nsus mentes.\n\nPero el tiempo me dará la razón\nporque, aunque no sea santo,\nhablo con profecías:\n\npues “toda vida\nculmina en la muerte”\n\ny aunque no sepa si\nte gusta lo que escribo\nestoy seguro\nque algún día\nmorirás,\n\npero\n“nadie es profeta en su propia tierra”\n\ny\nmis palabras\nse disuelven en la humedad del aire.\n\nCálido, el Caribe\noprime el arte.\n\nSu sol\ntan agobiante,\n\nque con cariño remanente\nde noche\nacaricia al indigente\ny a mí\nno me deja dormir,\n\ndespierta a las nubes\nque emergen del mar.\nBailando,\nimitan el vaivén\nde las olas\ne inspiran\na la brisa\na cargar melodías cromáticas\nque no me dejan deprimir.\n\nImpone el buen clima\nsu alegría\nsobre los que queremos ver\nla vida color gris;\n\nsu calidez impide\nla creación\nde arte\nque no sea feliz.\n\nCon optimismo\nllena de brillo\nun lienzo opaco.\n\nYo mismo\nhe cometido este pecado,\n\npues\nhe notado que\naunque el cielo se oscurezca\nsolo con escuchar\nel grito de\nuna negra\nme pongo feliz.",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 30,
        "name": "inspiracion",
        "title": "Inspiración",
        "body": "La soledad.\nSentir que has vivido\ntoda la vida solo;\ntoda la vida sin amante.\n\nSaber que la muerte\nsepara la carne del deseo;\nencerrado en el cofre\nde un dios cambiante.\n\nEl olvido.\nInterpretar el recuerdo\ncomo único testigo\nde la realidad.\n\nSin memoria,\n¿cómo diferenciar\nlo que no se recuerda\nde lo que nunca ha existido?\n\nLo inevitable.\nLa dicotomía de la vida,\nsu propósito\nen la muerte.\n\nInfructuoso buscar\ninmortalidad en el arte,\nsi ni un dios sigue eterno\ncuando se abandona su culto.\n\nLa nada.\nSentir que has malgastado\nel significado\nque tú mismo has creado.\n\nSaber que has vivido sin amigos,\nfamilia, dios\nni amante.\n\nLa soledad.\nLa única\nque acompaña al escritor\ncuando observa en silencio,\napartado.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 31,
        "name": "marea_baja",
        "title": "Marea Baja",
        "body": "Criaturas marinas,\nnocturnas y abisales.\n\nA flote,\npesadillas existenciales.\n¿Qué son ellas\ny por qué se alimentan de mí?\n¿Qué es el mar,\ny cómo cabe tanto\nen mis sueños?\n\nCriaturas marinas,\nnocturnas y sin alma.\n\nA flote,\ntraumas de la infancia,\nser la suma\nde sobras de personalidad.\nLos demás\nconstruyen su inmortalidad\nsobre el recuerdo ajeno.\n\nCriaturas marinas,\nnocturnas y divinas.\n\nA flote,\npensamientos:\n¿Cuándo sueño soy un dios?\n— Y cuando despierto —\n¿Dios estará soñando?\n¿Qué le causa pesadillas a Dios,\nlos humanos?\n\nCriaturas marinas,\nnocturnas y sensibles.\n\nA flote,\n“nuevas ideas”,\nreciclaje de arquetipos.\nLa originalidad es autoengaño;\nla creatividad,\nla descripción\nde lo que ya todos hemos sentido\ncon palabras que a nadie\nse le han ocurrido.\n\nCriaturas marinas,\nnocturnas e invisibles.\n\nNadan en mis sueños,\nvagan en mis pensamientos;\nahí se nutren,\ny empiezan a crecer.\nTú no las ves,\ntú no las oyes,\npero ahí están,\nocultas bajo mi piel.\n\nCriaturas que\nhablan, nadan\ny observan.\n\nHablan, vagan\ny ríen.\n\nHablan, nadan\ny se alimentan de mí.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 32,
        "name": "la_casa_de_las_goteras",
        "title": "La Casa de las Goteras",
        "body": "Goteras sobre masas de periódico y tela;\nhace días empezó a apestar.\n\nEl hedor es denso y distrae,\ncomo testigo del tiempo\nque no se detiene.\n\nLa humedad se eleva\ny se escurre entre grietas,\npor las paredes hasta el techo;\n\ncomo profetizando\nque, desde los cimientos,\ntodo se desmoronará.\n\nEn cama,\nparece que fuera así.\n\nAtento\nobservo el techo,\nesperando que escombros\ncaigan sobre mí.\n\nHe somatizado la carga anímica,\neso tumor blanco y baboso\nno para de crecer.\n\nSe acomoda en mis cuencas\ny no me deja ver.\n\nY como mi paz mental\ndepende de mi lucidez,\nno tener claridad\n\nme hace sentir denso y pesado,\ndifícil de maniobrar.\n\nCegado,\natraigo pensamientos cubiertos\npor neblina gris,\ny ruido blanco.\n\nComo un mar de gente\nhasta el techo,\nsusurrando\ntodos al mismo tiempo.\n\nSin saber\nquién dice qué;\n\nsin escuchar\nuna voz conocida,\nsin ver\nun rostro familiar.\n\nEs el universo\nqueriendo colapsar\ndentro de mi pecho.\n\nEs todo\nprecipitado hacia un punto pequeño;\nun golpe seco,\nuna implosión gradual\n\nMi gravedad atrapando masa\ny dilatando el tiempo,\n\nsin abstracción, ni emociones.\nPura materia fugaz.\n\nSon mis propios pensamientos\narremetiendo contra mí\n\nFinalmente,\nla luz se extingue y\nlas estrellas se despiden del atardecer…\n\nMe detengo,\nalgo golpea mi cara.\nNo sé si cemento o agua.",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 33,
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "body": "Una amante,\nuna musa\nun sol, una estrella.\n\nLa inspiración disruptiva\nque alimenta el poema.",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 34,
        "name": "die_rosenrot",
        "title": "Die Rosenrot",
        "body": "Ya habías abierto tus pétalos\ny andabas despreocupada,\nregándolos por ahí;\ndía y noche\nbailabas,\nacaparando miradas\ny enamorando al sol.\n\nRosa roja\ncomo sangre\nsadomasoquista,\ncolor intenso e indecente\ncomo el deseo de poseerte,\nde clavarme tus espinas,\ncada una de ellas\nsolo por el placer\nde volver a sentir.\n\nClavar unas en mi lengua\npara no halagar\notra flor.\n\nOtras en mi cuello,\ncomo penitente por el arte.\n\nY solo una en mi mente,\nsuficiente para no olvidar\nque idealizaba una vida\njunto a ti.\n\nLastimosamente, rosa,\nya no eres roja,\nno como recordaba.\n\nHas rapado cada pétalo\ny ya solo\nquedan espinas.\n\nTe has marchitado,\ny no parece\nque te vayas a detener.\n\nAun así,\nsería un privilegio\nverte morir,\n\nporque vives orgánica.\nNo eres plástica\ncomo aquellas\nque buscan acaparar el sol.\n\nPor eso,\nme gustaría\npresenciar tu muerte,\n\no la nuestra.\n\nSi lo permites,\ncon gusto te apretaría con suficiente fuerza\npara desangrar mi pecho sobre ti.\n\nSer mártir,\nsolo para que vivas\nlo que te queda\ncomo la rosa más roja.",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 35,
        "name": "reflexion_x",
        "title": "Reflexión X",
        "body": "¿Y si\nnuestra conciencia\nes el recuerdo\nde un yo\nagonizando\nen el presente?",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_poemas_para_mi = [
    {
        "poem_id": 36,
        "name": "entre_dientes",
        "title": "Entre Dientes",
        "body": "Evasivamente\nte respondo:\n«no tengo nada».\n¿No lo entiendes?\nSí “tengo algo”:\nme desmorono por dentro.\n\nTe digo:\n«no pasa nada».\n¿Qué no ha pasado?\n¿Acaso no lo ves?\nSiento que\nno puede ocurrir\nnada peor.\n\nTe evito con un\n«solo estoy cansado».\n¡Despierta!\nA gritos te dejo saber\nque estoy aburrido\nde lo cotidiano.\n\nTe explico\n«El nihilismo “esto” …\nNihilismo “aquello”».\nTe estoy diciendo\n—no en broma—\nque no le encuentro\nsentido a la vida.\n\nTe comparto\notro de mis pensamientos:\n\n“Ansío la muerte”,\naunque nunca lo escuches,\nlo grito entre dientes.",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 37,
        "name": "lounova",
        "title": "Lounová",
        "body": "Solía preguntarte:\n¿por qué eres tan perfecta?\nAhora pienso:\n¿por qué me gustas tanto?\n\nQuisiera saberlo,\nen serio,\npara que dejara de ser así;\nporque\n«la ignorancia te hace feliz»\ny el conocimiento de tu ausencia\nme desgarra las entrañas,\nel espíritu,\nla mente\ny el alma.\n\nCada mensaje tuyo\nes una pequeña dosis\nque aumenta mi dependencia a ti;\nadicto a una ilusión,\nadicto a tu recuerdo.\n\nAdicción\nque calmo\ncon autoengaño:\nla única opción, real,\nque siempre ha estado ahí.\n\nPero no es sano\neludir la realidad\npara fantasear contigo.\n\nDebo aceptar que fuiste\nun dulce sueño\nque se olvida al despertar.\n\nSolo me queda,\nen contra de cada impulso,\nconvencerme de que\nya no eres mi musa,\nque quizá\nnunca lo fuiste,\ny despedirme.\n\nUn adiós\nnunca sonó tan agrio.",
        "cover_url": poemas_para_mi_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 38,
        "name": "novia",
        "title": "Novia",
        "body": "De madrugada\nel insomnio induce un transitorio en mí.\nHace dos segundos,\napoyado en tus caderas,\nbuscaba constelaciones en tus pecas;\nun segundo después,\ndesperté.\n\nLa realidad me susurró.\n—No hay caderas, no hay pecas.\nNo hay pelo, ojos ni piel;\nrojo, verde ni blanco.\n\nY ahora,\npor la comisura de mi ojo,\nse fugan lágrimas.\nBoca arriba miro,\nmás allá del techo,\nhacia mi destino:\n\nLa soledad y la frustración.\n\nPorque cuando pude\nno era el tiempo de Dios.\nY hoy que quiero, sé\nque, a causa mía,\nno has sido, no eres\ny estoy convencido\nque tampoco serás.",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 39,
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "body": "Mal viajado, mi mente es poseída\npor una macabra melodía infantil; arte puro y diabólico.\n¿El himno de mis traumas?\nReverbera en mi pecho, se sobrepone a sus palabras, a mis canciones.\nEs poderosa y no sé por qué. Trato de ignorarla\npero cada movimiento asemeja su forma.\nUn arquetipo, un concepto, un símbolo.\n¿Subliminal, ancestral?\nUn talismán rectangular grande y arqueado\ncon un cuadrado en su base.\n[ZPLPLPLYK], [ZPLPLPLYK].\nPalabras que no entiendo, palabras que\nno puedo pronunciar;\nun ritmo en 5/4\nen el que no logro encajar.\nGolpes de negras que me impactan\ndanzando en rituales de santería.\nLa Sardana de las Brujas,\ndescalzas sobre mi halo,\nlo ensucian, se pudre.\nMe dañan la mente para que las acepte,\nporque me han escogido\n«Santo»\nsegún su pagana providencia.\nBloquean mis plegarias,\nbloquean a Dios.\nRecobro la conciencia por intervalos cortos,\ncada vez más cerca del suelo.\nMe acuesto frente al sofá,\nme arrastro hacia el baño.\nRecobro la conciencia de mi frustración\ntirado besando el piso.\nRecobro el sentido del dolor\nvomitando sangre.\n¿Mala hierba o placebo?\nNo importa, somatizo el viaje.\n[ZPLPLPLYK], [ZPLPLPLYK].\nCantos chillones, sollozos graves,\ngemidos no temperados,\ncadenas que se arrastran.\nUn compás de amalgama\ncompuesto por amplios matices\nde emociones fuertes.\nLanzo la mirada al pasillo\nmientras me arrastro por el marco\ny llamo a Frank.\nUn grito que se ahoga buscándolo\nen la lejanía creciente.\nCuando logra verme,\nya en el infinito,\nNo puede contener la risa.\nMis gimoteos nunca llegaron a sus oídos,\nsolo la patética imagen\nde un pretencioso que se perdió\nen sus propios pensamientos.\nImagen que comparten las musas,\ntapan sus delicadas boquitas\npara ocultar risotadas depravadas.\nMorbosas observan\nel espectáculo más bochornoso:\nun «artista»\narrastrándose por el suelo,\ntodo por encontrar un poco de inspiración.\n¿Qué obtuve?\n[ZPLPLPLYK], [ZPLPLPLYK].\nArmonías, melodías,\nritmos que no entiendo…\nPalabras que no soy capaz de escribir,\nun mal viaje que no quiero repetir\ny el temor de que todo\nhaya sido producto\nde mi propia mente.",
        "cover_url": poemas_para_mi_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 40,
        "name": "miketta",
        "title": "Miketta",
        "body": "Eres la primera artista\nque he acariciado\ncon indecencia,\nrasguños\nde mis manos “mágicas”\nde guitarrista\nfrustrado.\n\nY aunque\nsangraste,\nme impresionó\ntu nobleza:\nno sentiste dolor,\nsentiste vergüenza.\n\nVergüenza por dos dedos\nmanchados de sangre,\npor tu mordida\nen mi brazo.\nVergüenza\npor\nmostrar tus deseos\nde forma natural.\n\nVergüenza que veo\ny me hace sentir culpable.\n\nEres la inocencia\ny bondad\nque necesito\ncorromper.\n\nDeseo desatar los nudos\nque mantienen tu mente\natada a los clichés.\n\nPresentarte a mis musas:\nla realidad,\nel insomnio, la tristeza\ny la depresión.\n\nInvitarlas a que\ninspiren tus obras,\nnuestra futura\nhistoria:\nla única carta\nde desamor\nque me interesa leer.\n\nTe detallo\ncon detenimiento\npara comprender\nel porqué de\ntus lágrimas.\n\nTe detallo\ncon detenimiento\npara saber qué\nquieres escuchar.\n\nTe digo que soy\ntodo un caballero\nmientras metódicamente\npaseo mis yemas\nsobre tu lomo.\n\nMe di cuenta de cómo\nacariciar tu tatuaje;\ny tú,\nde que realmente\ntraigo intenciones\nde hacerte daño.",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 41,
        "name": "manipulacion",
        "title": "Manipulación",
        "body": "Ayer te mordí un pezón\ny creo que envenené tu pecho.\n\nAparentemente fue profundo\ny llegó a tus pulmones,\nporque hoy andas\nrespirando con dificultad,\ncomo agonizando.\n\nMe detallas erráticamente\ncon una mirada\napagada,\nbuscándole explicaciones\na mi forma de actuar.\n\nLa esperanza de encontrar\nmi bondad.\n\nMe da lástima\nverte lamentar\nla inexorable insatisfacción\nde tu búsqueda.\n\nNo encontrarás nada bueno\nen mí,\nsolo diezmarás tu fe.\n\nPero te entiendo.\nDespués de todo,\ndel veneno\nse obtiene el antídoto.\n\n—Con nuevos traumas—.\n¿Qué vacío buscas llenar?",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 42,
        "name": "insuperable",
        "title": "Insuperable",
        "body": "Increíble,\ncuatro años\ny sigues siendo\nun pensamiento recurrente.\n\nUn olor fugaz\nque guardo en mis pulmones.\n\nLa acidez constante\nque quema mi paladar.\n\nUna implosión incesante\nreverberando en mi pecho.\n\nEl vacío\nque no me siento listo para llenar.\n\nTrato de hacerlo\nreconstruyéndote con palabras,\npero inevitablemente\ncaigo en el suelo común,\nreventándome con fuerza\ncontra la realidad:\n\nQue tú no estás,\nque te necesito,\ny que, aunque eres la musa perfecta,\nno soy suficiente para ti.\n\nPorque no he logrado\ncombinar las palabras perfectas\npara inmortalizar tu belleza.\n\nPorque no he logrado\nbajarte del Parnaso\npara exhibirte ante los incrédulos\ne insensibles.\n\nTal vez,\npor eso no merezca tenerte;\no simplemente\nno me he esforzado\nlo suficiente.\n\nNo he consagrado mi vida\na inmortalizar la tuya,\nescribiendo el poema perfecto.\n\nNi han presionado mis dedos\ncon suficiente fuerza\nel teclado hasta sangrar.\n\nSi no he arriesgado mi vida\npara llegar a donde estás,\n\ncómo podría ser tan hipócrita\npara luego decirte\nque moriría por ti?",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 43,
        "name": "abuela",
        "title": "Abuela",
        "body": "Me siento un poco hipócrita\nrecibiendo el\n“sentido pésame”.\n\nYo nunca fui apegado a ella\ny honestamente\nno me siento mal\npor su muerte.\n\nDe hecho, me siento tranquilo\nporque su agonía terminó.\n\nPor eso,\ndeberían acercarse con un\n“lamento que sufriera\nen sus últimos momentos”.\n\nEso sí es consuelo,\npodría creer que es\nun comentario sincero.\n\nPorque la empatía\nnace de entender el dolor ajeno,\n\ny aunque no la quise,\nsiento tristeza\nporque la vi sufrir.\n\nDesahuciada\ncon una lagrima\nnos dio a entender\nque sufrió al aceptar su muerte.\n\nAl menos en ella\nencontró liberación\ny ya no hay más sufrimiento,\n\no bueno\núnicamente queda\nel de los que vivos\nlloran su muerte.",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 44,
        "name": "balcon",
        "title": "Balcón",
        "body": "Si se te antoja saltar, llámame\ny nos tiramos los dos.\n\nAsí verás que no miento,\ncuando te digo:\n\"el amor es una decisión\";\n\nque, si me das tu mano,\nme aferraría a ella el resto de mi vida,\n\ny que aceptar la muerte,\nno es tan difícil,\nsi te tengo junto a mí.",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 1,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_book_ii_eng = [
    {
        "poem_id": 1,
        "name": "god",
        "title": "God",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 2,
        "name": "identity",
        "title": "Identity",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 3,
        "name": "spica",
        "title": "Spica",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 4,
        "name": "moral",
        "title": "Moral",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 5,
        "name": "exhortation",
        "title": "Exhortation",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 6,
        "name": "writers_voice",
        "title": "Writer's Voice",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 7,
        "name": "defeatism",
        "title": "Defeatism",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 8,
        "name": "rat_utopia",
        "title": "Rat Utopia",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 9,
        "name": "reflection_ii",
        "title": "Reflection II",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 10,
        "name": "reflection_iii",
        "title": "Reflection III",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 11,
        "name": "reflection_iv",
        "title": "Reflection IV",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 12,
        "name": "reflection_xii",
        "title": "Reflection XII",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 13,
        "name": "its_not_enough",
        "title": "It's not enough",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 14,
        "name": "czech",
        "title": "Czech",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 15,
        "name": "hatred",
        "title": "Hatred",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 16,
        "name": "she",
        "title": "She",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 17,
        "name": "half_red_lucky_pack",
        "title": "Half Red Lucky Pack",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 18,
        "name": "reflection_ix",
        "title": "Reflection IX",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_book_i_eng = [
    {
        "poem_id": 19,
        "name": "nostalgia",
        "title": "Nostalgia",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 20,
        "name": "a_sad_world",
        "title": "A Sad World",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 21,
        "name": "acrylic",
        "title": "Acrylic",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 22,
        "name": "cliche",
        "title": "Cliché",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 23,
        "name": "cliche_ii",
        "title": "Cliché II",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 24,
        "name": "teeth",
        "title": "Teeth",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 25,
        "name": "monotony",
        "title": "Monotony",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 26,
        "name": "stitch",
        "title": "Stitch",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 27,
        "name": "weariness",
        "title": "Weariness",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 28,
        "name": "another_form_of_pain",
        "title": "Another Form of Pain",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 29,
        "name": "caribbean",
        "title": "Caribbean",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 30,
        "name": "inspiration",
        "title": "Inspiration",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 31,
        "name": "low_tide",
        "title": "Low Tide",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 32,
        "name": "the_house_of_leaks",
        "title": "The House of Leaks",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 33,
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 34,
        "name": "the_red_rose",
        "title": "The Red rose",
        "body": "",
        "cover_url": libro_ii_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 35,
        "name": "reflection_x",
        "title": "Reflection X",
        "body": "",
        "cover_url": libro_ii_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_poemas_para_mi_eng = [
    {
        "poem_id": 36,
        "name": "between_teeth",
        "title": "Between Teeth",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 37,
        "name": "lounova",
        "title": "Lounová",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "pages": 2,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 38,
        "name": "girlfriend",
        "title": "Girlfriend",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 39,
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "pages": 3,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 40,
        "name": "miketta",
        "title": "Miketta",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 41,
        "name": "manipulation",
        "title": "Manipulation",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 42,
        "name": "unforgettable",
        "title": "Unforgettable",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 43,
        "name": "grandmother",
        "title": "Grandmother",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "poem_id": 44,
        "name": "balcony",
        "title": "Balcony",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "ig_url": "",
        "language_id": 2,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]


book_content = [
    {"content_id": 1, "book_id": 1},
    {"content_id": 2, "book_id": 1},
    {"content_id": 3, "book_id": 1},
    {"content_id": 4, "book_id": 1},
    {"content_id": 5, "book_id": 1},
    {"content_id": 6, "book_id": 1},
    {"content_id": 7, "book_id": 1},
    {"content_id": 8, "book_id": 1},
    {"content_id": 9, "book_id": 1},
    {"content_id": 10, "book_id": 1},
    {"content_id": 11, "book_id": 1},
    {"content_id": 12, "book_id": 1},
    {"content_id": 13, "book_id": 1},
    {"content_id": 14, "book_id": 1},
    {"content_id": 15, "book_id": 1},
    {"content_id": 16, "book_id": 1},
    {"content_id": 17, "book_id": 1},
    {"content_id": 18, "book_id": 1},
    {"content_id": 1, "book_id": 4},
    {"content_id": 2, "book_id": 4},
    {"content_id": 3, "book_id": 4},
    {"content_id": 4, "book_id": 4},
    {"content_id": 5, "book_id": 4},
    {"content_id": 6, "book_id": 4},
    {"content_id": 7, "book_id": 4},
    {"content_id": 8, "book_id": 4},
    {"content_id": 9, "book_id": 4},
    {"content_id": 10, "book_id": 4},
    {"content_id": 11, "book_id": 4},
    {"content_id": 12, "book_id": 4},
    {"content_id": 13, "book_id": 4},
    {"content_id": 14, "book_id": 4},
    {"content_id": 15, "book_id": 4},
    {"content_id": 16, "book_id": 4},
    {"content_id": 17, "book_id": 4},
    {"content_id": 18, "book_id": 4},
    {"content_id": 19, "book_id": 2},
    {"content_id": 20, "book_id": 2},
    {"content_id": 21, "book_id": 2},
    {"content_id": 22, "book_id": 2},
    {"content_id": 23, "book_id": 2},
    {"content_id": 24, "book_id": 2},
    {"content_id": 25, "book_id": 2},
    {"content_id": 26, "book_id": 2},
    {"content_id": 27, "book_id": 2},
    {"content_id": 28, "book_id": 2},
    {"content_id": 29, "book_id": 2},
    {"content_id": 30, "book_id": 2},
    {"content_id": 31, "book_id": 2},
    {"content_id": 32, "book_id": 2},
    {"content_id": 33, "book_id": 2},
    {"content_id": 34, "book_id": 2},
    {"content_id": 35, "book_id": 2},
    {"content_id": 19, "book_id": 5},
    {"content_id": 20, "book_id": 5},
    {"content_id": 21, "book_id": 5},
    {"content_id": 22, "book_id": 5},
    {"content_id": 23, "book_id": 5},
    {"content_id": 24, "book_id": 5},
    {"content_id": 25, "book_id": 5},
    {"content_id": 26, "book_id": 5},
    {"content_id": 27, "book_id": 5},
    {"content_id": 28, "book_id": 5},
    {"content_id": 29, "book_id": 5},
    {"content_id": 30, "book_id": 5},
    {"content_id": 31, "book_id": 5},
    {"content_id": 32, "book_id": 5},
    {"content_id": 33, "book_id": 5},
    {"content_id": 34, "book_id": 5},
    {"content_id": 35, "book_id": 5},
    {"content_id": 36, "book_id": 3},
    {"content_id": 37, "book_id": 3},
    {"content_id": 38, "book_id": 3},
    {"content_id": 39, "book_id": 3},
    {"content_id": 40, "book_id": 3},
    {"content_id": 41, "book_id": 3},
    {"content_id": 42, "book_id": 3},
    {"content_id": 43, "book_id": 3},
    {"content_id": 36, "book_id": 6},
    {"content_id": 37, "book_id": 6},
    {"content_id": 38, "book_id": 6},
    {"content_id": 39, "book_id": 6},
    {"content_id": 40, "book_id": 6},
    {"content_id": 41, "book_id": 6},
    {"content_id": 42, "book_id": 6},
    {"content_id": 43, "book_id": 6},
    {"content_id": 44, "book_id": 6},
    {"content_id": 45, "book_id": 4},
    {"content_id": 46, "book_id": 4},
    {"content_id": 47, "book_id": 4},
    {"content_id": 48, "book_id": 4},
    {"content_id": 49, "book_id": 4},
    {"content_id": 50, "book_id": 4},
    {"content_id": 51, "book_id": 4},
    {"content_id": 52, "book_id": 4},
    {"content_id": 53, "book_id": 4},
    {"content_id": 54, "book_id": 4},
    {"content_id": 55, "book_id": 4},
    {"content_id": 56, "book_id": 4},
    {"content_id": 57, "book_id": 4},
    {"content_id": 58, "book_id": 4},
    {"content_id": 59, "book_id": 4},
    {"content_id": 60, "book_id": 4},
    {"content_id": 61, "book_id": 4},
    {"content_id": 62, "book_id": 4},
    {"content_id": 63, "book_id": 5},
    {"content_id": 64, "book_id": 5},
    {"content_id": 65, "book_id": 5},
    {"content_id": 66, "book_id": 5},
    {"content_id": 67, "book_id": 5},
    {"content_id": 68, "book_id": 5},
    {"content_id": 69, "book_id": 5},
    {"content_id": 70, "book_id": 5},
    {"content_id": 71, "book_id": 5},
    {"content_id": 72, "book_id": 5},
    {"content_id": 73, "book_id": 5},
    {"content_id": 74, "book_id": 5},
    {"content_id": 75, "book_id": 5},
    {"content_id": 76, "book_id": 5},
    {"content_id": 77, "book_id": 5},
    {"content_id": 78, "book_id": 5},
    {"content_id": 79, "book_id": 5},
    {"content_id": 80, "book_id": 6},
    {"content_id": 81, "book_id": 6},
    {"content_id": 82, "book_id": 6},
    {"content_id": 83, "book_id": 6},
    {"content_id": 84, "book_id": 6},
    {"content_id": 85, "book_id": 6},
    {"content_id": 86, "book_id": 6},
    {"content_id": 87, "book_id": 6},
    {"content_id": 88, "book_id": 6},
]

language = [
    {"id": 1, "name": "spanish", "original_name": "español"},
    {"id": 2, "name": "english", "original_name": "english"},
]


book = [
    {
        "name": "libro_ii",
        "title": "Libro II",
        "pdf_url": libro_ii_pdf,
        "cover_url": libro_ii_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_i",
        "title": "Libro I",
        "pdf_url": libro_i_pdf,
        "cover_url": libro_i_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "poemas_para_mi",
        "title": "Poemas para mí",
        "pdf_url": poemas_para_mi_pdf,
        "cover_url": poemas_para_mi_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_ii__book_ii",
        "title": "Libro II | Book II",
        "pdf_url": libro_ii__book_ii_pdf,
        "cover_url": libro_ii_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_i__book_i",
        "title": "Libro I | Book I",
        "pdf_url": libro_i__book_i_pdf,
        "cover_url": libro_i_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "poemas_para_mi_poems_for_me",
        "title": "Poemas para mí | Poems for me",
        "pdf_url": poemas_para_mi__poems_for_me_pdf,
        "cover_url": poemas_para_mi_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_libro_ii = [
    {
        "name": "dios",
        "title": "Dios",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "identidad",
        "title": "Identidad",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "spica",
        "title": "Spica",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "moral",
        "title": "Moral",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "exhortacion",
        "title": "Exhortación",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "voz_de_escritor",
        "title": "Voz de Escritor",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "derrotismo",
        "title": "Derrotismo",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "utopia_de_ratas",
        "title": "Utopía de Ratas",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_II",
        "title": "Reflexión II",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_III",
        "title": "Reflexión III",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_IV",
        "title": "Reflexión IV",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_XII",
        "title": "Reflexión XII",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "no_es_suficiente",
        "title": "No es Suficiente",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "checa",
        "title": "Checa",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "odio",
        "title": "Odio",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "ella",
        "title": "Ella",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "media_de_lucky_rojo",
        "title": "Media de Lucky Rojo",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_IX",
        "title": "Reflexión IX",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_libro_i = [
    {
        "name": "nostalgia",
        "title": "Nostalgia",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "un_mundo_triste",
        "title": "Un Mundo Triste",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "acrilico",
        "title": "Acrílico",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche",
        "title": "Cliché",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche_II",
        "title": "Cliché II",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "dientes",
        "title": "Dientes",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "monotonia",
        "title": "Monotonía",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "stitch",
        "title": "Stitch",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cansancio",
        "title": "Cansancio",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "otra_forma_de_dolor",
        "title": "Otra Forma de Dolor",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "caribe",
        "title": "Caribe",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "inspiracion",
        "title": "Inspiración",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "marea_baja",
        "title": "Marea Baja",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "la_casa_de_las_goteras",
        "title": "La Casa de las Goteras",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "die_rosenrot",
        "title": "Die Rosenrot",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_X",
        "title": "Reflexión X",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_poemas_para_mi = [
    {
        "name": "entre_dientes",
        "title": "Entre Dientes",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "lounova",
        "title": "Lounová",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "novia",
        "title": "Novia",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "miketta",
        "title": "Miketta",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "manipulacion",
        "title": "Manipulación",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "insuperable",
        "title": "Insuperable",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "abuela",
        "title": "Abuela",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "balcon",
        "title": "Balcón",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_image_book_ii = [
    {
        "content_id": 1,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dios.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 2,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'identidad.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 3,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'spica.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 4,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'moral.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 5,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'exhortacion.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 6,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'voz_de_escritor.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 7,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'derrotismo.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 8,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'utopia_de_ratas_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 8,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'utopia_de_ratas_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 9,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_ii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 10,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_iii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 11,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_iv.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 12,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_xii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 13,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'no_es_suficiente.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 14,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'checa.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 15,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'odio.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 16,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'ella.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 17,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'media_de_lucky_rojo.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 18,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_ix.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
content_image_book_i = [
    {
        "content_id": 19,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'nostalgia.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 20,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'un_mundo_triste.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 21,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'acrilico.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 22,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cliche.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 23,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cliche_ii.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 24,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dientes_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 24,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dientes_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 25,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'monotonia_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 25,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'monotonia_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 26,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'stitch.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 27,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cansancio_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 27,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cansancio_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 28,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'otra_forma_de_dolor_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 28,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'otra_forma_de_dolor_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 29,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 29,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 29,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe_p3.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 30,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'inspiracion_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 30,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'inspiracion_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 31,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'marea_baja_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 31,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'marea_baja_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 32,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 32,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 32,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras_p3.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 33,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'femme_fatale.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 34,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'die_rosenrot_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 34,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'die_rosenrot_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 35,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_x.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

content_image_poemas_para_mi = [
    {
        "content_id": 36,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'entre_dientes.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 37,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'lounova_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 37,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'lounova_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 38,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'novia.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 39,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 39,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 39,
        "pages": 3,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 40,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'miketta_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 40,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'miketta_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 41,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'manipulacion.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 42,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'insuperable_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 42,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'insuperable_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 43,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'abuela_p1.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 43,
        "pages": 2,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'abuela_p2.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "content_id": 44,
        "pages": 1,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'balcon.jpg')}",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
poem = poems_libro_ii + poems_libro_i + poems_poemas_para_mi
content = (
    content_book_ii
    + content_book_i
    + content_poemas_para_mi
    + content_book_ii_eng
    + content_book_i_eng
    + content_poemas_para_mi_eng
)
content_image = (
    content_image_book_ii + content_image_poemas_para_mi + content_image_book_i
)
