import datetime


azure_blob_token = "?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-02-10T11:26:21Z&st=2024-01-23T03:26:21Z&spr=https&sig=mpe3aTH4DxOM8ZEDo0Loin8OBMnqvrjFUaPAXFVyNjs%3D"
azure_blob_cover = "https://radowski.blob.core.windows.net/cover/<blob_name>"
azure_blob_book = "https://radowski.blob.core.windows.net/book/<blob_name>"
azure_blob_poem = "https://radowski.blob.core.windows.net/poem/<blob_name>"

libro_i_cover = azure_blob_cover.replace("<blob_name>", "libro_i.png")
libro_ii_cover = azure_blob_cover.replace("<blob_name>", "libro_ii.png")
poemas_para_mi_cover = azure_blob_cover.replace("<blob_name>", "poemas_para_mi.png")
libro_i_pdf = azure_blob_book.replace("<blob_name>", "libro_i.pdf")
libro_ii_pdf = azure_blob_book.replace("<blob_name>", "libro_i.pdf")
poemas_para_mi_pdf = azure_blob_book.replace("<blob_name>", "poemas_para_mi.pdf")
libro_i__book_i_pdf = azure_blob_book.replace("<blob_name>", "libro_i__book_i.pdf")
libro_ii__book_ii_pdf = azure_blob_book.replace("<blob_name>", "libro_ii__book_ii.pdf")
poemas_para_mi__poems_for_me_pdf = azure_blob_book.replace(
    "<blob_name>", "poemas_para_mi__poems_for_me.pdf"
)

content_book_ii = [
    {
        "name": "dios",
        "title": "Dios",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dios.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "identidad",
        "title": "Identidad",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'identidad.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "spica",
        "title": "Spica",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'spica.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "moral",
        "title": "Moral",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'moral.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "exhortacion",
        "title": "Exhortación",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'exhortacion.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "voz_de_escritor",
        "title": "Voz de Escritor",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'voz_de_escritor.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "derrotismo",
        "title": "Derrotismo",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'derrotismo.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "utopia_de_ratas",
        "title": "Utopía de Ratas",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'utopia_de_ratas.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_ii",
        "title": "Reflexión II",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_ii.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_iii",
        "title": "Reflexión III",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_iii.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_iv",
        "title": "Reflexión IV",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_iv.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_xii",
        "title": "Reflexión XII",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_xii.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "no_es_suficiente",
        "title": "No es Suficiente",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'no_es_suficiente.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "checa",
        "title": "Checa",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'checa.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "odio",
        "title": "Odio",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'odio.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "ella",
        "title": "Ella",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'ella.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "media_de_lucky_rojo",
        "title": "Media de Lucky Rojo",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'media_de_lucky_rojo.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_ix",
        "title": "Reflexión IX",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_ix.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
content_book_i = [
    {
        "name": "nostalgia",
        "title": "Nostalgia",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'nostalgia.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "un_mundo_triste",
        "title": "Un Mundo Triste",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'un_mundo_triste.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "acrilico",
        "title": "Acrílico",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'acrilico.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche",
        "title": "Cliché",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cliche.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche_ii",
        "title": "Cliché II",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cliche_ii.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "dientes",
        "title": "Dientes",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'dientes.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "monotonia",
        "title": "Monotonía",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'monotonia.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "stitch",
        "title": "Stitch",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'stitch.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cansancio",
        "title": "Cansancio",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'cansancio.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "otra_forma_de_dolor",
        "title": "Otra Forma de Dolor",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'otra_forma_de_dolor.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "caribe",
        "title": "Caribe",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'caribe.jpg')}",
        "pages": 3,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "inspiracion",
        "title": "Inspiración",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'inspiracion.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "marea_baja",
        "title": "Marea Baja",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'marea_baja.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "la_casa_de_las_goteras",
        "title": "La Casa de las Goteras",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'la_casa_de_las_goteras.jpg')}",
        "pages": 3,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'femme_fatale.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "die_rosenrot",
        "title": "Die Rosenrot",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'die_rosenrot.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_x",
        "title": "Reflexión X",
        "body": "",
        "cover_url": libro_ii_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'reflexion_x.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]
content_poemas_para_mi = [
    {
        "name": "entre_dientes",
        "title": "Entre Dientes",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'entre_dientes.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "lounova",
        "title": "Lounová",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'lounova.jpg')}",
        "pages": 2,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "novia",
        "title": "Novia",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'novia.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'zplplplyk.jpg')}",
        "pages": 3,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "miketta",
        "title": "Miketta",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'miketta.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "manipulacion",
        "title": "Manipulación",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'manipulacion.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "insuperable",
        "title": "Insuperable",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'insuperable.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "abuela",
        "title": "Abuela",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'abuela.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "balcon",
        "title": "Balcón",
        "body": "",
        "cover_url": poemas_para_mi_cover,
        "img_url": f"{azure_blob_poem.replace('<blob_name>', 'balcon.jpg')}",
        "pages": 1,
        "ig_url": "",
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poem_content_language = [
    {"poem_id": 1, "content_id": 1, "language_id": 1},
    {"poem_id": 2, "content_id": 2, "language_id": 1},
    {"poem_id": 3, "content_id": 3, "language_id": 1},
    {"poem_id": 4, "content_id": 4, "language_id": 1},
    {"poem_id": 5, "content_id": 5, "language_id": 1},
    {"poem_id": 6, "content_id": 6, "language_id": 1},
    {"poem_id": 7, "content_id": 7, "language_id": 1},
    {"poem_id": 8, "content_id": 8, "language_id": 1},
    {"poem_id": 9, "content_id": 9, "language_id": 1},
    {"poem_id": 10, "content_id": 10, "language_id": 1},
    {"poem_id": 11, "content_id": 11, "language_id": 1},
    {"poem_id": 12, "content_id": 12, "language_id": 1},
    {"poem_id": 13, "content_id": 13, "language_id": 1},
    {"poem_id": 14, "content_id": 14, "language_id": 1},
    {"poem_id": 15, "content_id": 15, "language_id": 1},
    {"poem_id": 16, "content_id": 16, "language_id": 1},
    {"poem_id": 17, "content_id": 17, "language_id": 1},
    {"poem_id": 18, "content_id": 18, "language_id": 1},
    {"poem_id": 19, "content_id": 19, "language_id": 1},
    {"poem_id": 20, "content_id": 20, "language_id": 1},
    {"poem_id": 21, "content_id": 21, "language_id": 1},
    {"poem_id": 22, "content_id": 22, "language_id": 1},
    {"poem_id": 23, "content_id": 23, "language_id": 1},
    {"poem_id": 24, "content_id": 24, "language_id": 1},
    {"poem_id": 25, "content_id": 25, "language_id": 1},
    {"poem_id": 26, "content_id": 26, "language_id": 1},
    {"poem_id": 27, "content_id": 27, "language_id": 1},
    {"poem_id": 28, "content_id": 28, "language_id": 1},
    {"poem_id": 29, "content_id": 29, "language_id": 1},
    {"poem_id": 30, "content_id": 30, "language_id": 1},
    {"poem_id": 31, "content_id": 31, "language_id": 1},
    {"poem_id": 32, "content_id": 32, "language_id": 1},
    {"poem_id": 33, "content_id": 33, "language_id": 1},
    {"poem_id": 34, "content_id": 34, "language_id": 1},
    {"poem_id": 35, "content_id": 35, "language_id": 1},
    {"poem_id": 36, "content_id": 36, "language_id": 1},
    {"poem_id": 37, "content_id": 37, "language_id": 1},
    {"poem_id": 38, "content_id": 38, "language_id": 1},
    {"poem_id": 39, "content_id": 39, "language_id": 1},
    {"poem_id": 40, "content_id": 40, "language_id": 1},
    {"poem_id": 41, "content_id": 41, "language_id": 1},
    {"poem_id": 42, "content_id": 42, "language_id": 1},
    {"poem_id": 43, "content_id": 43, "language_id": 1},
    {"poem_id": 44, "content_id": 44, "language_id": 1},
]

poem_book_language = [
    {"poem_id": 1, "book_id": 1, "language_id": 1},
    {"poem_id": 2, "book_id": 1, "language_id": 1},
    {"poem_id": 3, "book_id": 1, "language_id": 1},
    {"poem_id": 4, "book_id": 1, "language_id": 1},
    {"poem_id": 5, "book_id": 1, "language_id": 1},
    {"poem_id": 6, "book_id": 1, "language_id": 1},
    {"poem_id": 7, "book_id": 1, "language_id": 1},
    {"poem_id": 8, "book_id": 1, "language_id": 1},
    {"poem_id": 9, "book_id": 1, "language_id": 1},
    {"poem_id": 10, "book_id": 1, "language_id": 1},
    {"poem_id": 11, "book_id": 1, "language_id": 1},
    {"poem_id": 12, "book_id": 1, "language_id": 1},
    {"poem_id": 13, "book_id": 1, "language_id": 1},
    {"poem_id": 14, "book_id": 1, "language_id": 1},
    {"poem_id": 15, "book_id": 1, "language_id": 1},
    {"poem_id": 16, "book_id": 1, "language_id": 1},
    {"poem_id": 17, "book_id": 1, "language_id": 1},
    {"poem_id": 18, "book_id": 1, "language_id": 1},
    {"poem_id": 19, "book_id": 2, "language_id": 1},
    {"poem_id": 20, "book_id": 2, "language_id": 1},
    {"poem_id": 21, "book_id": 2, "language_id": 1},
    {"poem_id": 22, "book_id": 2, "language_id": 1},
    {"poem_id": 23, "book_id": 2, "language_id": 1},
    {"poem_id": 24, "book_id": 2, "language_id": 1},
    {"poem_id": 25, "book_id": 2, "language_id": 1},
    {"poem_id": 26, "book_id": 2, "language_id": 1},
    {"poem_id": 27, "book_id": 2, "language_id": 1},
    {"poem_id": 28, "book_id": 2, "language_id": 1},
    {"poem_id": 29, "book_id": 2, "language_id": 1},
    {"poem_id": 30, "book_id": 2, "language_id": 1},
    {"poem_id": 31, "book_id": 2, "language_id": 1},
    {"poem_id": 32, "book_id": 2, "language_id": 1},
    {"poem_id": 33, "book_id": 2, "language_id": 1},
    {"poem_id": 34, "book_id": 2, "language_id": 1},
    {"poem_id": 35, "book_id": 2, "language_id": 1},
    {"poem_id": 36, "book_id": 3, "language_id": 1},
    {"poem_id": 37, "book_id": 3, "language_id": 1},
    {"poem_id": 38, "book_id": 3, "language_id": 1},
    {"poem_id": 39, "book_id": 3, "language_id": 1},
    {"poem_id": 40, "book_id": 3, "language_id": 1},
    {"poem_id": 41, "book_id": 3, "language_id": 1},
    {"poem_id": 42, "book_id": 3, "language_id": 1},
    {"poem_id": 43, "book_id": 3, "language_id": 1},
    {"poem_id": 44, "book_id": 3, "language_id": 1},
    {"poem_id": 1, "book_id": 4, "language_id": 3},
    {"poem_id": 2, "book_id": 4, "language_id": 3},
    {"poem_id": 3, "book_id": 4, "language_id": 3},
    {"poem_id": 4, "book_id": 4, "language_id": 3},
    {"poem_id": 5, "book_id": 4, "language_id": 3},
    {"poem_id": 6, "book_id": 4, "language_id": 3},
    {"poem_id": 7, "book_id": 4, "language_id": 3},
    {"poem_id": 8, "book_id": 4, "language_id": 3},
    {"poem_id": 9, "book_id": 4, "language_id": 3},
    {"poem_id": 10, "book_id": 4, "language_id": 3},
    {"poem_id": 11, "book_id": 4, "language_id": 3},
    {"poem_id": 12, "book_id": 4, "language_id": 3},
    {"poem_id": 13, "book_id": 4, "language_id": 3},
    {"poem_id": 14, "book_id": 4, "language_id": 3},
    {"poem_id": 15, "book_id": 4, "language_id": 3},
    {"poem_id": 16, "book_id": 4, "language_id": 3},
    {"poem_id": 17, "book_id": 4, "language_id": 3},
    {"poem_id": 18, "book_id": 4, "language_id": 3},
    {"poem_id": 19, "book_id": 5, "language_id": 3},
    {"poem_id": 20, "book_id": 5, "language_id": 3},
    {"poem_id": 21, "book_id": 5, "language_id": 3},
    {"poem_id": 22, "book_id": 5, "language_id": 3},
    {"poem_id": 23, "book_id": 5, "language_id": 3},
    {"poem_id": 24, "book_id": 5, "language_id": 3},
    {"poem_id": 25, "book_id": 5, "language_id": 3},
    {"poem_id": 26, "book_id": 5, "language_id": 3},
    {"poem_id": 27, "book_id": 5, "language_id": 3},
    {"poem_id": 28, "book_id": 5, "language_id": 3},
    {"poem_id": 29, "book_id": 5, "language_id": 3},
    {"poem_id": 30, "book_id": 5, "language_id": 3},
    {"poem_id": 31, "book_id": 5, "language_id": 3},
    {"poem_id": 32, "book_id": 5, "language_id": 3},
    {"poem_id": 33, "book_id": 5, "language_id": 3},
    {"poem_id": 34, "book_id": 5, "language_id": 3},
    {"poem_id": 35, "book_id": 5, "language_id": 3},
    {"poem_id": 36, "book_id": 6, "language_id": 3},
    {"poem_id": 37, "book_id": 6, "language_id": 3},
    {"poem_id": 38, "book_id": 6, "language_id": 3},
    {"poem_id": 39, "book_id": 6, "language_id": 3},
    {"poem_id": 40, "book_id": 6, "language_id": 3},
    {"poem_id": 41, "book_id": 6, "language_id": 3},
    {"poem_id": 42, "book_id": 6, "language_id": 3},
    {"poem_id": 43, "book_id": 6, "language_id": 3},
    {"poem_id": 44, "book_id": 6, "language_id": 3},
]

language = [
    {"id": 1, "name": "spanish"},
    {"id": 2, "name": "english"},
    {"id": 3, "name": "spanish-english"},
]

book = [
    {
        "name": "libro_ii",
        "title": "Libro II",
        "pdf_url": libro_ii_pdf,
        "cover_url": libro_ii_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_i",
        "title": "Libro I",
        "pdf_url": libro_i_pdf,
        "cover_url": libro_i_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "poemas_para_mi",
        "title": "Poemas para mí",
        "pdf_url": poemas_para_mi_pdf,
        "cover_url": poemas_para_mi_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_ii__book_ii",
        "title": "Libro II | Book II",
        "pdf_url": libro_ii__book_ii_pdf,
        "cover_url": libro_ii_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "libro_i__book_i",
        "title": "Libro I | Book I",
        "pdf_url": libro_i__book_i_pdf,
        "cover_url": libro_i_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "poemas_para_mi_poems_for_me",
        "title": "Poemas para mí | Poems for me",
        "pdf_url": poemas_para_mi__poems_for_me_pdf,
        "cover_url": poemas_para_mi_cover,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_libro_ii = [
    {
        "name": "dios",
        "title": "Dios",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "identidad",
        "title": "Identidad",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "spica",
        "title": "Spica",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "moral",
        "title": "Moral",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "exhortacion",
        "title": "Exhortación",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "voz_de_escritor",
        "title": "Voz de Escritor",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "derrotismo",
        "title": "Derrotismo",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "utopia_de_ratas",
        "title": "Utopía de Ratas",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_II",
        "title": "Reflexión II",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_III",
        "title": "Reflexión III",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_IV",
        "title": "Reflexión IV",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_XII",
        "title": "Reflexión XII",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "no_es_suficiente",
        "title": "No es Suficiente",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "checa",
        "title": "Checa",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "odio",
        "title": "Odio",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "ella",
        "title": "Ella",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "media_de_lucky_rojo",
        "title": "Media de Lucky Rojo",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_IX",
        "title": "Reflexión IX",
        "cover_url": libro_ii_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_libro_i = [
    {
        "name": "nostalgia",
        "title": "Nostalgia",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "un_mundo_triste",
        "title": "Un Mundo Triste",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "acrilico",
        "title": "Acrílico",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche",
        "title": "Cliché",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cliche_II",
        "title": "Cliché II",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "dientes",
        "title": "Dientes",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "monotonia",
        "title": "Monotonía",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "stitch",
        "title": "Stitch",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "cansancio",
        "title": "Cansancio",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "otra_forma_de_dolor",
        "title": "Otra Forma de Dolor",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "caribe",
        "title": "Caribe",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "inspiracion",
        "title": "Inspiración",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "marea_baja",
        "title": "Marea Baja",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "la_casa_de_las_goteras",
        "title": "La Casa de las Goteras",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "femme_fatale",
        "title": "Femme Fatale",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "die_rosenrot",
        "title": "Die Rosenrot",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "reflexion_X",
        "title": "Reflexión X",
        "cover_url": libro_i_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poems_poemas_para_mi = [
    {
        "name": "entre_dientes",
        "title": "Entre Dientes",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "lounova",
        "title": "Lounová",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "novia",
        "title": "Novia",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "zplplplyk",
        "title": "[ZPLPLPLYK]",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "miketta",
        "title": "Miketta",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "manipulacion",
        "title": "Manipulación",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "insuperable",
        "title": "Insuperable",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "abuela",
        "title": "Abuela",
        "cover_url": poemas_para_mi_cover,
        "is_active": True,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
    {
        "name": "balcon",
        "title": "Balcón",
        "cover_url": poemas_para_mi_cover,
        "is_active": False,
        "created_at": datetime.datetime.now(),
        "updated_at": datetime.datetime.now(),
    },
]

poem = poems_libro_ii + poems_libro_i + poems_poemas_para_mi
content = content_book_ii + content_book_i + content_poemas_para_mi
